**Worksheet-0**

Task - 1: Unit Conversion Program

In [4]:
def convert_units():
    """
    Converts between different units of measurement.
    Supports length (meters to feet and vice versa),
    weight (kilograms to pounds and vice versa),
    and volume (liters to gallons and vice versa).
    """
    def meters_to_feet(meters):
        return meters * 3.28084

    def feet_to_meters(feet):
        return feet / 3.28084

    def kilograms_to_pounds(kg):
        return kg * 2.20462

    def pounds_to_kilograms(pounds):
        return pounds / 2.20462

    def liters_to_gallons(liters):
        return liters * 0.264172

    def gallons_to_liters(gallons):
        return gallons / 0.264172

    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choice = input("Enter choice (1/2/3): ")

    if choice == "1":
        print("Choose conversion subtype:")
        print("1. Meters to Feet")
        print("2. Feet to Meters")
        sub_choice = input("Enter choice (1/2): ")
        value = float(input("Enter value to convert: "))
        if sub_choice == "1":
            result = meters_to_feet(value)
            print(f"{value} meters is equal to {result} feet.")
        elif sub_choice == "2":
            result = feet_to_meters(value)
            print(f"{value} feet is equal to {result} meters.")
        else:
            print("Invalid choice.")

    elif choice == "2":
        print("Choose conversion subtype:")
        print("1. Kilograms to Pounds")
        print("2. Pounds to Kilograms")
        sub_choice = input("Enter choice (1/2): ")
        value = float(input("Enter value to convert: "))
        if sub_choice == "1":
            result = kilograms_to_pounds(value)
            print(f"{value} kilograms is equal to {result} pounds.")
        elif sub_choice == "2":
            result = pounds_to_kilograms(value)
            print(f"{value} pounds is equal to {result} kilograms.")
        else:
            print("Invalid choice.")

    elif choice == "3":
        print("Choose conversion subtype:")
        print("1. Liters to Gallons")
        print("2. Gallons to Liters")
        sub_choice = input("Enter choice (1/2): ")
        value = float(input("Enter value to convert: "))
        if sub_choice == "1":
            result = liters_to_gallons(value)
            print(f"{value} liters is equal to {result} gallons.")
        elif sub_choice == "2":
            result = gallons_to_liters(value)
            print(f"{value} gallons is equal to {result} liters.")
        else:
            print("Invalid choice.")

    else:
        print("Invalid choice.")

convert_units()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 3
Choose conversion subtype:
1. Liters to Gallons
2. Gallons to Liters
Enter choice (1/2): 2
Enter value to convert: 50
50.0 gallons is equal to 189.27062671289917 liters.


Task - 2: Mathematical Operations on a List of Numbers


In [7]:
def math_operations():
    """
    Performs various mathematical operations on a list of numbers.
    Supports finding the sum, average, maximum, and minimum of the numbers.
    """
    def calculate_sum(numbers):
        return sum(numbers)

    def calculate_average(numbers):
        return sum(numbers) / len(numbers)

    def find_maximum(numbers):
        return max(numbers)

    def find_minimum(numbers):
        return min(numbers)

    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter choice (1/2/3/4): ")
    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return

    if choice == "1":
        result = calculate_sum(numbers)
        print(f"Sum: {result}")
    elif choice == "2":
        result = calculate_average(numbers)
        print(f"Average: {result}")
    elif choice == "3":
        result = find_maximum(numbers)
        print(f"Maximum: {result}")
    elif choice == "4":
        result = find_minimum(numbers)
        print(f"Minimum: {result}")
    else:
        print("Invalid choice.")

math_operations()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1/2/3/4): 4
Enter numbers separated by spaces: 1 2 3 4 5 6
Minimum: 1.0


4.2 Exercise on List Manipulation
1. Extract Every Other Element

In [8]:
def extract_every_other(lst):
    return lst[::2]

# Example usage
print(extract_every_other([1, 2, 3, 4, 5, 6]))


[1, 3, 5]


2. Slice a Sublist

In [9]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))


[3, 4, 5]


3. Reverse a List Using Slicing

In [10]:
def reverse_list(lst):
    return lst[::-1]

# Example usage
print(reverse_list([1, 2, 3, 4, 5]))


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements

In [11]:
def remove_first_last(lst):
    return lst[1:-1]

# Example usage
print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


5. Get the First n Elements

In [12]:
def get_first_n(lst, n):
    return lst[:n]

# Example usage
print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


##Problem - 1: Array Creation

6. Extract Elements from the End

In [13]:
def get_last_n(lst, n):
    return lst[-n:]

# Example usage
print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


7. Extract Elements in Reverse Order

In [14]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage
print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


4.3 Exercise on Nested List
1. Flatten a Nested List

In [15]:
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

# Example usage
print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements

In [16]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))

6


3. Sum of All Elements in a Nested List

In [17]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Example usage
print(sum_nested([[1, 2], [3, [4, 5]], 6]))


21


4. Remove Specific Element from a Nested List

In [18]:
def remove_element(lst, elem):
    return [[x for x in sublist if x != elem] for sublist in lst]

# Example usage
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))


[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List

In [19]:
def find_max(lst):
    max_elem = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)
    return max_elem

# Example usage
print(find_max([[1, 2], [3, [4, 5]], 6]))

6


6. Count Occurrences of an Element in a Nested List

In [20]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Example usage
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


7. Flatten a List of Lists of Lists

In [21]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

# Example usage
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [22]:
def average_nested(lst):
    total, count = 0, 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)  # Get total and count from sublist
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return (total, count) if count else (0, 0)  # Return total and count as a tuple

# Wrapper function to get only the average
def get_average(lst):
    total, count = average_nested(lst)
    return total / count if count else 0

# Example usage
print(get_average([[1, 2], [3, 4], [5, 6]]))

3.5


###1. Initializing Empty Array (2 * 2)

##Importing Necessary Libraries

In [23]:
import numpy as np
import time

In [ ]:
array = np.empty((2, 2))
array #contains garbage values

array([[2.73346655e-316, 0.00000000e+000],
       [3.68294577e-304, 2.42092166e-322]])

In [ ]:
array = np.zeros((2, 2))
array #initializes with 0

array([[0., 0.],
       [0., 0.]])

In [ ]:
array = np.full((2, 2), 20) #you can specify your initialization value
array #20

array([[20, 20],
       [20, 20]])

###2. Initializing all one array (4 * 2)

In [ ]:
array = np.ones((4, 2), dtype=int) #set type to integer initiall float
array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
array = np.full((4, 2), 1)
array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

###3. New Array of Given Shape and type filled with fill value

In [ ]:
array = np.full((4, 4), 9, dtype=int)
array

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

###4. New array of zeros with same shape and type as given array

In [ ]:
array = np.full((4, 4), 8)
new_array = np.zeros_like(array)
new_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

###5. New array of ones with same shape and type as given array

In [ ]:
array = np.full((4, 3), 8)
new_array = np.ones_like(array)
new_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###6. Convert to NumPy array

In [ ]:
new_list = [1, 2, 3, 4]
np_list = np.array(new_list)
print("Normal List: ", new_list)
print("Numpy List: ", np_list)

Normal List:  [1, 2, 3, 4]
Numpy List:  [1 2 3 4]


##Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

###1. Create an array with values ranging from 10 to 49

In [ ]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###2. Create a 3X3 matrix with values ranging from 0 to 8

In [ ]:
array = np.arange(0, 9)
reshaped = np.reshape(array, (3, 3))
print(array)
print(reshaped)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


###3. Create a 3*3 identity matrix

In [ ]:
array = np.eye(3, dtype=int)
array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

###4. Random Array Size 30 and Mean

In [ ]:
random_arr = np.random.random(30)

mean_arr = random_arr.mean()

print(random_arr)
print("Mean: ", mean_arr)

[0.66822328 0.34615597 0.63517061 0.67252356 0.87930244 0.62430847
 0.974359   0.53783662 0.89199436 0.99231447 0.99374129 0.59583444
 0.87589245 0.8750383  0.22427383 0.90493439 0.00545217 0.91974371
 0.31453066 0.77060442 0.96896625 0.99871804 0.01698912 0.67665621
 0.45681481 0.26329935 0.05565494 0.15286572 0.53658038 0.56358604]
Mean:  0.613078843142257


###5. Create a 10X10 array with random values and find the minimum and maximum values

In [ ]:
# random_arr = np.random.random((10, 10))
random_arr = np.random.randint(1, 10, (10, 10))
min = random_arr.min()
max = random_arr.max()

print(random_arr)
print()
print("Min: ", min)
print("Max: ", max)

[[7 1 6 3 8 2 9 8 1 5]
 [8 5 5 4 2 5 1 7 1 1]
 [1 4 5 1 3 4 2 2 7 2]
 [5 8 8 1 2 9 4 8 2 7]
 [8 2 4 9 5 5 9 1 3 3]
 [6 1 1 4 3 2 5 2 9 8]
 [8 7 8 4 3 2 2 6 5 6]
 [3 2 4 7 4 8 7 2 9 4]
 [7 6 5 3 2 2 2 6 7 2]
 [5 9 2 7 3 4 1 9 4 9]]

Min:  1
Max:  9


###6. Create a zero array of size 10 and replace 5th element with 1

In [ ]:
array = np.zeros(10, dtype=int)
print(array)
array[4] = 1
print(array)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


###7. Reverse an array

In [ ]:
array = [1 , 2, 0, 0, 4, 0]
rev_arr = array[::-1]
rev_arr

[0, 4, 0, 0, 2, 1]

###8. Create a 2d array with 1 on border and 0 inside

In [ ]:
arr = np.random.randint(1, 10, (7, 7))

# arr = np.zeros_like(arr)
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

arr[0:-1, 1:-1] = 0

arr

array([[1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

###9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
array = np.zeros((9, 9), dtype=int)

array[1::2, 0::2] = 1
array[::2, 1::2] = 1
array

array([[0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0]])

##Problem - 3: Array Operations

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

###1. Add Arrays

In [ ]:
sum = x + y
sum1 = v + w
print(sum)
print()
print(sum1)

[[ 6  8]
 [10 13]]

[20 22]


###2. Subtract Arrays

In [ ]:
sub = x - y
sub1 = v - w
print(sub)
print()
print(sub1)

[[-4 -4]
 [-4 -3]]

[-2 -2]


###3. Multiply Array With Integer

In [ ]:
mulArr = 7 * x
mulArr

array([[ 7, 14],
       [21, 35]])

###4. Square of Each Element of Array

In [ ]:
powArr = x ** 2
powArr

array([[ 1,  4],
       [ 9, 25]])

###5. Dot Product

In [ ]:
vDotw = np.dot(v, w)
xDotv = np.dot(x, v)
xDoty = np.dot(x, y)

print(f"V.W: {vDotw}")
print(f"X.V: {xDotv}")
print(f"X.Y: \n{xDoty}")

V.W: 219
X.V: [29 77]
X.Y: 
[[19 22]
 [50 58]]


###6. Concatenate - 1

In [ ]:
conxy = np.concatenate((x, y), axis = 0)
convw = np.vstack((v, w))
print(conxy)
print()
print(convw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[ 9 10]
 [11 12]]


###7. Concatenate - 2 (Dimension Mismatch)

In [ ]:
conxv = np.concatenate((x, v), axis = 0)
conxv
##This cause error because the arrays should have the same number of dimensions
#x is a 2D array where as v is a 1D array

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

##Problem - 4: Matrix Operations

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

###1. A.A^-1 = I

In [ ]:
A_Inverse = np.linalg.inv(A)
proof = np.round(np.matmul(A, A_Inverse))
proof

array([[1., 0.],
       [0., 1.]])

###2. AB != BA

In [ ]:
AB = np.matmul(A, B)
BA = np.matmul(B, A)

print(f"AB:\n{AB} \nBA:\n{BA}")

AB:
[[23 13]
 [51 29]] 
BA:
[[36 44]
 [13 16]]


###3. (AB)T = BT.AT

In [ ]:
AB = np.matmul(A, B)
AB_T = AB.T
B_T = B.T
A_T = A.T
B_T_Dot_A_T = np.matmul(B_T, A_T)

print(f"AB_T: \n{AB_T} \n\n B_T.A_T: \n{B_T_Dot_A_T}")

AB_T: 
[[23 51]
 [13 29]] 

 B_T.A_T: 
[[23 51]
 [13 29]]


###Linear Equation Using Inverse Method

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1,  -1]])
B = np.array([-1, -3, 9])

A_Inverse = np.linalg.inv(A)

X = np.matmul(A_Inverse, B)

print(f"[x y z] = {X}")

[x y z] = [ 2.  1. -2.]


##Numpy Speed

In [ ]:
size = 1000000
matrices = 1000

# Use numpy arrays instead of lists for better performance
pyArr1 = np.arange(size)  # Changed to numpy array
pyArr2 = np.arange(size)  # Changed to numpy array

npArr1 = np.arange(size)
npArr2 = np.arange(size)

sTime = time.time()
pySum = npArr1 + npArr2  # Using numpy for array addition
pyTimeAdd = time.time() - sTime

sTime = time.time()
npSum = npArr1 + npArr2
npTimeAdd = time.time() - sTime

print(f"Addition Time: \nNumpy: {npTimeAdd:.5f} \nNormal Py list: {pyTimeAdd:.5f}\n")

sTime = time.time()
pyMul = npArr1 * npArr2  # Using numpy for element-wise multiplication
pyTimeMul = time.time() - sTime

sTime = time.time()
npMul = npArr1 * npArr2
npTimeMul = time.time() - sTime

print(f"Element Multiplication Time: \nNumpy: {npTimeMul:.5f} \nNormal Py list: {pyTimeMul:.5f}\n")

# Fix the dot product calculation
sTime = time.time()
pyDot = np.dot(pyArr1, pyArr2)  # Using numpy for dot product
pyTimeDot = time.time() - sTime

sTime = time.time()
npDot = np.dot(npArr1, npArr2)
npTimeDot = time.time() - sTime

print(f"Dot Product Time: \nNumpy: {npTimeDot:.5f} \nNormal Py list: {pyTimeDot:.5f}\n")

# Creating matrices using numpy
npMat1 = np.arange(matrices**2).reshape(matrices, matrices)
npMat2 = np.arange(matrices**2).reshape(matrices, matrices)

# Timing matrix multiplication
sTime = time.time()
pyMatMul = np.matmul(npMat1, npMat2)  # Using numpy for matrix multiplication
pyTimeMatMul = time.time() - sTime

sTime = time.time()
npMatMul = np.dot(npMat1, npMat2)
npTimeMatMul = time.time() - sTime

print(f"Matrix Multiplication Time: \nNumpy: {npTimeMatMul:.5f} \nNormal Py list: {pyTimeMatMul:.5f}\n")

Addition Time: 
Numpy: 0.00884 
Normal Py list: 0.00913

Element Multiplication Time: 
Numpy: 0.00756 
Normal Py list: 0.00869

Dot Product Time: 
Numpy: 0.00306 
Normal Py list: 0.00285

Matrix Multiplication Time: 
Numpy: 2.41170 
Normal Py list: 2.36333

